apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: grafana
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'grafana'
      static_configs:
      - targets: ['34.41.216.68:80']

   - job_name: 'pgdb'
     static_configs:
     - targets: ['34.60.156.135:9187']
