apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.54.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.enable-lifecycle"          # <— allows reload
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prom-data
              mountPath: /prometheus

        - name: configmap-reload
          image: jimmidyson/configmap-reload:v0.12.0
          args:
            - --volume-dir=/etc/prometheus
            - --webhook-url=http://localhost:9090/-/reload
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus

      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: prom-data
          emptyDir: {}


