apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: grafana
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090        # Service port
    targetPort: 9090  # Container port
  type: ClusterIP     # change to LoadBalancer if you want external access
