apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: grafana
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      protocol: TCP
    # If you really need a second port, keep it and name it:
    # - name: prom-admin
    #   port: 9093
    #   targetPort: 9093
    #   protocol: TCP

